- app/src/main/java/com/ku_stacks/ku_ring/analytics/EventAnalytics.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/feedback/FeedbackViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/setting_notification/SettingNotificationViewModel.kt
- app/src/main/res/values/strings.xml
- fcm token을 가져오지 못하면 throw Exception 하여 Crashlytics에 전송되도록 했었다.
- 일반 사용자들에게는 이슈가 되지 않지만 플레이스토어 업데이트 요청할 때마다 구글 검수측에서 Crash가 발생하였고 앱의 안정성이 문제가 있는것 처럼 보이게 된다.
- 구글측에서 Crash나는 원인은 한 에뮬레이터 또는 기기에서 너무 많은 fcm registration을 요청하면 발생하는것으로 보인다.
- 관련 링크 : https://stackoverflow.com/questions/47529977/firebase-token-error-too-many-registrations
- EventAnalytics 모듈에서 errorEvent()를 만들어 커스텀 에러 로그를 따로 전송할 수 있도록 하였다.
- FeedbackViewModel, SettingNotificationViewModel에서 fcm token을 가져오지 못하면 crashlytics 대신 analytics로 전송하고, 화면에 Toast 메세지를 보여준다.
> [이슈] Fcm Token 쪽에서 Crash 이슈

- .idea/misc.xml
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeActivity.kt
- app/src/main/res/layout/activity_notice.xml
- 사용자가 웹뷰 스크롤을 내리면서 조금이라도 더 넓은 화면을 활용할 수 있도록 기존에는 CoordinatorLayout + CollapsingToobarLayout 을 상단바를 적용했었다.
- 건국대학교의 홈페이지의 웹뷰(모바일용의 좁은 화면)에서는 공지 내에 너비가 넓은 이미지가 있는 경우 스크린 가로폭을 이미지에 맞추고 있었음
- 그로 인해 넓은 이미지가 있는 경우 가로 스크롤이 생김
- 이미지 없이 텍스트만 있는 공지에서는 문제가 되지 않음
-  CoordinatorLayout + CollapsingToobarLayout 을 사용하면서 가로 스크롤이 있는 웹뷰를 보여줄때 가로스크롤이 잘 되지 않는 이슈가 있었다. (정확히 가로 방향 스크롤을 해야지만 스크롤이 되는 현상)
- 다른 앱들을 참고해 봤을 때(에브리타임, 카카오톡) 웹뷰에서 CoordinatorLayout은 적용하는 경우는 찾지 못했음
- 사용하던 CoordinatorLayout을 포기하고 일반 상단바로 적용
- 웹뷰 내에서 zoom In/Out 가능하도록 변경
- 이미지 너비가 넓은 경우에는 최대 이미지너비가 zoom out 할 수 있는 최대 너비가 된다.
- 웹뷰 내에서 가로스크롤과 세로스크롤이 자연스럽게 적용 
- 상단바에서 X 버튼 추가, 쿠링 아이콘 중앙으로 위치 이동
> [디자인 수정] 공지 웹뷰 화면에서 CollapsingToolbarLayout 제거, 줌 in/out 가능하도록 개선

- app/src/main/java/com/ku_stacks/ku_ring/ui/feedback/FeedbackActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/home/category/NoticeViewHolder.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/modified_external_library/AppearanceAnimator.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/modified_external_library/TagContainerLayout.java
- app/src/main/res/layout/item_notice.xml
- app/src/main/res/layout/item_notification.xml
- 공지리스트 화면, 내알림 화면에서 Tag 들을 위한 TagContainerLayout을 사용하고 있음
- 해당 라이브러리 링크 : https://github.com/whilu/AndroidTagView
- Tag의 상위 ViewGroup인 뷰홀더를 클릭했을대 TagContainerLayout은 클릭을 해도 반응이 없는 이슈가 있었음
- Tag 의 공간뿐만이 아니라 Tag들을 가지고 있는 Container가 무반응이며, 영역이 꽤 넓었다
- RootLayout > TagContainerLayout > Tag 의 계층 구조로 UI가 구성되어 있는데, TagContainerLayout 쪽에서 발생한 터치 이벤트를 RootLayout으로 전달하지 못했기 때문
- TagContainerLayout의 소스코드를 보면 ViewGroup을 상속받고 있으며, onInterceptTouchEvent(), onTouchEvent()를 재정의하고 있다.
- Library Author가 재정의 하려했던 의도 : Tag의 Drag 이벤트를 만들려하였기 때문
- 그러나 이 두 메서드를 overriding 할 때 부모의 매소드 기능을 없애버렸다.
- 따라서 일반적인 ViewGroup의 터치이벤트 처리가 안되고 있었다.
- Android 공식문서를 보면 ViewGroup의 터치 이벤트 처리는 특별히 주의하라고 하고 있다.
- https://developer.android.com/training/gestures/viewgroup?hl=ko
- 오픈소스인 TagContainerLayout 부분을 따로 클래스로 생성
- …
> [이슈] 공지리스트에서 Tag Layout 클릭시 반응이 없던 이슈 수정

- app/build.gradle
- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/DataMapperUtil.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/EntityToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ModelToUiModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/my_notification/ui_model/PushUiModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/StringUtil.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/UrlGenerator.kt
- app/src/main/res/layout/item_notification.xml
- app/src/test/java/com/ku_stacks/ku_ring/util/StringUtilTest.kt
현재 검색 소켓이 작동하지 않아 API URL만 수정했습니다. 
[Crashlytics 로그](https://console.firebase.google.com/u/0/project/ku-stack/crashlytics/app/android:com.ku_stacks.ku_ring/issues/28f84fa34f25ceef2bef18def2e567d5?time=last-ninety-days&versions=1.2.8%20(20)&sessionEventKey=64004DF401DD00010DBE21DE08CF40B5_1784296132468777733)를 분석한 결과 **보관함에 보관된 공지 중 `subject`가 빈 문자열인 `NoticeEntity`가 있다**는 결과를 얻었는데, 일반적인 흐름상 나올 수 없는 결과라 의문입니다. 
일단 앱이 강제 종료되지는 않게 하기 위해 `splitSubjectAndTag` 함수에 빈 문자열이 주어졌을 때  `NoSuchElementException` 대신 빈 문자열과 리스트 `Pair`를 반환하도록 수정했습니다.
이 문제는 계속 지켜볼 예정입니다.
> 원인: `PushEntity`에 `category`가 한글로 저장되기 때문이었습니다. (`bachleor` 대신 `학사`로 저장됨)
`PushEntity`와 `Push`에는 무조건 영어로 저장되게 수정했고, `PushContentUiModel`에는 사용자에게 보여주기 위해 한글로 변환하여 넘겨줍니다. `PushContentUiModel`의 `category` 변수의 이름도 한글임을 강조하기 위해 `categoryKor`로 …
> [수정] 공지 보관함 버그픽스

- app/build.gradle
그렇습니다.
`WEB_SOCKET_URL`은 어차피 웹소켓이 곧 제거될 예정이라 그대로 두었습니다.
> [수정] debug API의 base url을 수정

- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/CategoryPagerAdapter.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/category/HomeBaseFragment.kt
https://github.com/KU-Stacks/KU-Ring-Android/pull/28#discussion_r1133297538 에서 말씀드렸던, Fragment에 데이터를 Bundle로 전달하도록 수정한 PR입니다.
- fragment에 데이터를 생성자 대신 bundle로 전달
> [제안] fragment 에 데이터를 생성자 대신 bundle 로 전달

- app/src/main/java/com/ku_stacks/ku_ring/customview/ClearEditText.kt
- app/src/main/java/com/ku_stacks/ku_ring/customview/ClearableEditText.kt
- app/src/main/res/layout/fragment_search.xml
모두 지우기 기능을 지원하는 커스텀 뷰 `ClearableEditText`를 정의한 후, XML에서 `EditText`를 `ClearableEditText`로 교체했습니다.
> [추가] 검색어 모두 지우기 기능 추가

- app/build.gradle
디버깅 앱에서 복잡한 aws URL 대신 `api-test.ku-ring.com`을 사용합니다.
끝!
> [수정] 디버깅 API 도메인을 ku-ring.com으로 변경

- .idea/compiler.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Android Studio 버전별로 사용 가능한 AGP 버전이 다릅니다. 다람쥐 버전에서는 AGP 3.2-7.2 버전을 지원하므로 적당히 AGP 7.1 버전을 채용하고, 동시에 원래 목적이었던 gradle 버전도 Flamingo 지원 하한선인 7.2로 업데이트했습니다.
요약하면 다음과 같습니다.
* AGP: 7.0.2 -> 7.1 (Chipmunk, Flamingo 모두 지원)
* gradle: 7.0.2 -> 7.2 (Flamingo 하한선)
그런데 빌드 과정에서 Hilt 관련 문제가 있었습니다. Kotlin과 Hilt 버전을 업데이트하는 게 해결방법이라고 해서, 둘 다 업데이트했습니다. Kotlin 버전은 Android Studio 버전과 상관 없는 듯합니다. Hilt 버전업에 따라 ViewModel을 inject하는 `fragment-ktx` 라이브러리도 버전을 올렸습니다.
* Hilt: 2.39 -> 2.45
* Kotlin: 1.5.10 -> 1.8.21
* `fragment-ktx`: 1.4.0-alpha03 -> 1.5.0
그런데 빌드 과정에서 또 문제가 있어서;; 봤더니 `lifecycle-viewmodel-ktx` 라이브러리와 Hilt에 내장된 `lifecycle-viewmodel` 간의 충돌 문제가 있었습니다. `lifecycle-viewmodel-ktx` 라이브러리의 버전을 업데이트하여 해결했습니다.
* `lifecycle-viewmodel-ktx`: 2.3.1 -> 2.5.1
`.xml` 파일들은 Flamingo로 오면서 새로 추가된 파일이라고 합니다. 일단 커밋에는 포함했는데, 다람쥐 …
> [수정] gradle, AGP, kotlin, hilt 버전 업데이트

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/MainActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/onboarding/OnboardingActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/FcmUtil.kt
- 서버단에서 iOS 푸시알림 대응을 위해 데이터페이로드 방식에서 Notification 방식으로 변경되었음
- https://github.com/ku-ring/ku-ring-backend-web/pull/23/commits/fa7f5ef5443642412a76a2ef4439b3ff4b61b14f?diff=split&w=0
- 안드로이드앱이 foreground 상태일땐 파이어베이스의 onMessageReceived 이 호출되지만 background 상태일땐 호출되지 않는 현상 발생
변경 사항
- SplashActivity에서 받은 intent로 Notification 이벤트를 처리하도록 수정
- MyFireBaseMessagingService와 공통된 로직은 FcmUtil 클래스로 분리
- FcmUtil은 필요한 곳에서 주입 받을수 있도록 변경
참고 링크
https://firebase.google.com/docs/cloud-messaging/android/receive?hl=ko#override-onmessagereceived
> 백그라운드 Notification 클릭하여 앱 진입시 대응

- .idea/inspectionProfiles/Project_Default.xml
- app/build.gradle
- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/DepartmentClient.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/DepartmentService.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/request/DepartmentSubscribeRequest.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/EntityToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ResponseToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/model/Department.kt
- app/src/main/java/com/ku_stacks/ku_ring/di/RepositoryModule.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepository.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepositoryImpl.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/SubscribeRepository.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/SubscribeRepositoryImpl.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/SubscriptionUiModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/NonLazyGrid.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/SubscriptionDrawer.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/Subscriptions.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/theme/Color.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/theme/KuringTheme.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/theme/Typography.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/StateFlowUtil.kt
- app/src/main/res/layout/activity_edit_subscription.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/ku_stacks/ku_ring/TestingLiveDataExt.kt
- app/src/test/java/com/ku_stacks/ku_ring/repository/SubscribeRepositoryTest.kt
학과별 공지 기능의 일부로, 알림을 받을 학과를 고르는 화면이 필요함에 따라 개발하였습니다.
Compose 프레임워크를 사용하여 개발하였습니다. Preview를 함께 보시면 코드를 이해하는 데 도움이 될 듯합니다.
`EditSubscriptionActivity`에 있던 `RecyclerView`를 제거하고, Compose로 구현한 `Subscriptions`로 교체했습니다. 동시에 `ViewModel`에 있던 여러 `LiveData`도 `Flow`로 수정했습니다.
이전 PR에서 추가된 학과 데이터, 학과별 공지 데이터를 사용하여 구현하였습니다. 자세한 내용은 코멘트로 설명하겠습니다.
> [수정] 구독 화면 디자인 수정 및 학과 구독 기능 추가

- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/DepartmentNoticeFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/DepartmentNoticeViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/compose/DepartmentHeader.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/compose/DepartmentNoticeScreen.kt
* `선택한 학과`가 1개일 때에도 onClickListener가 작동합니다.
* `구독한 학과` 중 UI에서 보여줄 학과(`선택한 학과`)를 고르는 로직에 문제가 있었습니다. 구체적으로는 `선택한 학과`가 구독 취소되었음에도 불구하고 보여주려 한다던가, `선택한 학과`의 이름을 UI에 제대로 보여주지 못하는 문제가 있었습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/d352b833c208c05152539157ea5d4a7650a7e7a9: 이제 `선택한 학과`가 1개일 때 onClickListener가 작동하지 않습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/81ba921de9df0fae3e4ae788f27adeb5a21148a2: `선택한 학과`를 고르는 로직을 단순하게 수정했습니다.
> [수정] 학과별공지 로직 수정

- app/src/main/res/drawable/ic_notice_storage.xml
우선순위는 낮지만 작업내용도 간단하여 수정작업하였습니다.
- 공지리리스트탭의 공지보관함 아이콘 사이즈조정
|AS IS|TO BE|
|:---:|:---:|
|<img width="300" alt="image" src="https://github.com/ku-ring/KU-Ring-Android/assets/45001093/14aa9e5d-4374-432e-bc4e-cd1af6803c82">|<img width="300" alt="image" src="https://github.com/ku-ring/KU-Ring-Android/assets/45001093/2fcceb78-8c96-4a5d-86c2-4a73299eb387">|
> [수정] 공지보관함 아이콘 패딩 조정

- app/src/main/java/com/ku_stacks/ku_ring/data/api/response/SearchNoticeDataResponse.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/response/SearchNoticeListResponse.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/response/SearchStaffDataResponse.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/api/response/SearchStaffListResponse.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ResponseToModelMapper.kt
* `baseUrl` 필드에 전체 URL을 담아줍니다.
* 아직 검색 API에서는 response 구조에서 응답 리스트의 level이 1 줄어들지 않았습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/61efa118dbd16a787a8f5d1975c9fb29984a1dfd: baseUrl
* https://github.com/ku-ring/KU-Ring-Android/commit/1bc908b8a2337aacdec83a4761b7b5d6ef45061e: depth
> [수정] 검색 API 변경사항 대응

- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/db/PushEntity.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/EntityToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ModelToUiModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/model/Push.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/MainActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/my_notification/ui_model/PushUiModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/FcmUtil.kt
- app/src/test/java/com/ku_stacks/ku_ring/MockUtil.kt
- app/src/test/java/com/ku_stacks/ku_ring/persistence/PushDaoTest.kt
공지 알림을 터치했을 때 다음과 같이 공지 페이지가 보이지 않습니다.
원인은 서버에서 `baseUrl` 키 값에 전체 url을 넣어서 보내주는데, 앱에서는 base url을 받고 있다고 가정하여 이 뒤에 `articleId`를 덧붙였기 때문입니다.
구체적으로, 서버가 반환하는 url은 다음과 같으므로 이 url을 그대로 사용하면 문제가 없습니다.
```
https://www.konkuk.ac.kr/do/MessageBoard/ArticleRead.do?id=5b514fb
```
그런데 앱에서는 서버가 다음의 base url을 반환한다고 가정하여, 뒤에 `articleId`를 덧붙이고 있었습니다.
```
https://www.konkuk.ac.kr/do/MessageBoard/ArticleRead.do
```
결과적으로 앱에서 웹뷰를 열기 위해 사용한 URL은 다음과 같습니다.
```
https://www.konkuk.ac.kr/do/MessageBoard/ArticleRead.do?id=5b514fb?id=5b514fb
```
따라서 서버가 반환하는 url을 그대로 사용하도록 수정했습니다. 그런데 키 값이 `baseUrl`이라서 혼동을 불러일으킬 수 있으므로, 전체 url임을 명시적으로 보이기 위해 변수 이름은 `fullUrl`로 사용했습니다.
**단, DB의 column 이름은 변경하지 않았습니다**. 추후 서버에서 보내주는 키 값이 확정되면 한번에 바꾸려 합니다.
핫픽스로 적용되어야 할 것 같은데, target branch를 `develop`이 아니라 `main`으로 해야 할까요?
> [수정] 공지 알림을 터치했을 때 공지 페이지가 보이지 않던 현상 해결

- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ModelToUiModelMapper.kt
제목이 곧 내용입니다.
이 이유는 카테고리 문자열이 알파벳만으로 이루어졌을 때만 한국어로 번역했는데, 번역 로직에서 알파벳이 없는 경우도 고려하고 있기 때문에 조건문을 사용할 필요가 없습니다.
되려 `_`를 포함하는 `industry_university`가 `산학`으로 번역되지 않는 문제가 있었습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/f6a670ae951f6ac1d231cd44f10d472e8ddeae52 : `industry_university`가 `산학`으로 제대로 번역되지 않던 문제를 해결했습니다.
> [수정] 내 알림 화면에서 industry_university를 제대로 번역하지 않던 문제 해결

- app/proguard-rules.pro
- app/src/main/java/com/ku_stacks/ku_ring/data/api/request/DepartmentSubscribeRequest.kt
프로덕션 앱에서 학과를 구독해도, 구독한 결과가 서버에 반영되지 않습니다.
**난독화된 파라미터 이름이 request에 들어가고 있었기 때문입니다.** 
```json
{"a":["khistory","kugeo"]}
```
다른 request에서 문제가 없었던 이유는 `@SerializedName` 어노테이션으로 파라미터 이름을 지정하고 있었기 때문입니다. 이 어노테이션이 없으면 필드 이름이 그대로 파라미터 이름으로 사용됩니다. 
```Kotlin
data class FeedbackRequest(
@SerializedName(value = "id")
val token: String,
@SerializedName(value = "content")
val content: String
)
```
* https://github.com/ku-ring/KU-Ring-Android/commit/6ff2e993aa30fd3a1202a4e20c27fd0dd64caa02 : Proguard 난독화 규칙에서 모든 request 객체를 제외했습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/76b8ace71a1df2324626ac76c23b830e3159e7dd : 학과 구독 request의 파라미터 이름을 `@SerializedName`을 사용하여 명시적으로 지정했습니다.
> [수정] 학과 구독 request가 서버에 전달되지 않던 문제 해결

- app/src/main/java/com/ku_stacks/ku_ring/data/db/NoticeDao.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/FcmUtil.kt
https://kuring.atlassian.net/browse/KURING-43
알림으로 온 새 공지를 북마크할 수 없습니다.
알림으로 온 새 공지가 `NoticeEntity` 테이블에 저장되어 있지 않았기 때문입니다. 현재 로직상 공지를 북마크하려면 해당 공지가 DB에 존재해야 하는데, 기존 코드에서는 알림이 왔을 때 `PushEntity`만 저장하고 `NoticeEntity`는 저장하지 않았습니다.
`PushEntity`를 저장할 때 `NoticeEntity`도 함께 저장하도록 수정하면 됩니다.
브랜치, PR, 커밋 모두 `kuring-{티켓번호}`를 맨 앞에 붙여야 Jira에 연결됩니다. 이 PR에서는 커밋 앞에 접두사를 붙이지 않아서 Jira에서 커밋 목록을 확인할 수 없습니다.
커밋도 보이면 좋긴 한데.. 커밋 이름 앞에도 접두사를 붙여야 할까요?
> kuring-43 알림으로 온 공지를 북마크할 수 없던 문제 해결

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
알림 권한을 앱을 처음 실행할 때 얻지 않고, 두 번째로 실행할 때 또는 그 이후에 권한을 얻고 있습니다. Android 13(API 33)부터는 권한을 받지 않으면 알림을 보낼 수 없으므로 알림 권한을 앱 최초 실행 시에 받는 것이 바람직합니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/9f9c5a54859b9923a84918e5c5030351c923711c: Android 13에서 추가된 알림 권한을 정의했습니다. 현재 쿠링 앱은 API 31을 타겟팅하고 있어서 이 권한이 작동하지는 않지만, 향후 API 타겟을 상향 조정할 때 사용할 수 있도록 추가해 두었습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/9bfb321b19e2d95d8ce7225baf12845106b01bf3: API 32 이하에서는 Notification Channel을 만들 때 OS에서 알림 권한을 자동으로 요청합니다. 따라서 스플래시 화면에서 Notification Channel을 만들도록 수정했습니다.
https://salmonpack.tistory.com/32
> kuring-37 앱이 처음 실행될 때 알림 권한을 받도록 수정

- app/build.gradle
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/util/DateUtil.kt
- app/src/main/java/com/ku_stacks/ku_ring/work/ReEngagementNotificationWork.kt
- app/src/main/java/com/ku_stacks/ku_ring/work/ReengagementNotificationWork.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/ku_stacks/ku_ring/util/DateUtilTest.kt
오랫동안 앱을 실행하지 않았을 때 앱을 실행하도록 권유하는 알림(reengagement notification, 재참여 알림)을 보내는 경우가 있습니다. 시의성이 중요한 앱에서 그런 경우가 많습니다. 쿠링 앱도 공지를 바로바로 전달하는 걸 목표로 하는 만큼 재참여 알림을 보내자는 건의가 나왔고, 다른 팀원들도 동의하여 개발하게 되었습니다.
앱을 실행한 후 일주일이 되는 날 오후 12시에 알림을 보냅니다. 
앱을 실행할 때마다 알림을 보내는 백그라운드 work를 등록하는 방식으로 구현했습니다. 이전에 등록된 work가 있다면 새 work로 교체됩니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/da9201b044432227c1777eaaab0aae3d6fe97e6a: Jetpack WorkManager 의존성을 추가했습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/fbb12a3c004d38dfac3d11b995925af6017fa87b: 알림 제목 및 본문에 사용할 string 리소스를 추가했습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/49de72ca13c66ddea1ee9f4f2f1cce26ce18be33: N일 후의 주어진 시간을 나타내는 `Calendar` 객체를 반환하는 유틸 함수를 추가했습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/c6cfd23ca97411de49b7cf13191cb116 …
> kuring-62 [추가] 앱 재실행 유도 알림을 발송하는 기능 추가

- app/src/main/java/com/ku_stacks/ku_ring/data/db/DepartmentDao.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepository.kt
- app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepositoryImpl.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/fragment_subscribe/DepartmentSubscribeViewModel.kt
- app/src/test/java/com/ku_stacks/ku_ring/LocalDbAbstract.kt
- app/src/test/java/com/ku_stacks/ku_ring/MockUtil.kt
- app/src/test/java/com/ku_stacks/ku_ring/paging_source/DepartmentNoticeMediatorTest.kt
- app/src/test/java/com/ku_stacks/ku_ring/persistence/DepartmentDaoTest.kt
- app/src/test/java/com/ku_stacks/ku_ring/persistence/NoticeDaoTest.kt
- app/src/test/java/com/ku_stacks/ku_ring/persistence/PushDaoTest.kt
- app/src/test/java/com/ku_stacks/ku_ring/repository/DepartmentRepositoryTest.kt
서버에서 학과 이름이 바뀌어도(예: 문화컨텐츠 -> 문화콘텐츠) 로컬 DB에서 바뀐 이름을 저장하지 않습니다.
서버에서 학과 데이터를 가져올 때, 로컬 DB가 비어 있지 않다면 DB에 저장된 학과 중 이름이 바뀐 학과를 업데이트하면 됩니다.
코멘트로 설명하겠습니다.
> kuring-38 [수정] 서버에서 학과 이름이 바뀌었을 때 로컬 DB에도 반영하도록 수정

- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ModelToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/mapper/UiModelToModelMapper.kt
- app/src/main/java/com/ku_stacks/ku_ring/data/model/WebViewNotice.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/MainActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
공지 웹뷰를 보여주는 데 필요한 매개변수가 많아지면서, Intent에 데이터를 put, get하는 코드가 너무 길어졌습니다. 심지어 몇몇 필드는 아예 필요하지도 않습니다.
```Kotlin
intent?.getStringExtra(NoticeWebActivity.NOTICE_URL)?.let {
val articleId = intent.getStringExtra(NoticeWebActivity.NOTICE_ARTICLE_ID)
val category = intent.getStringExtra(NoticeWebActivity.NOTICE_CATEGORY)
val postedDate = intent.getStringExtra(NoticeWebActivity.NOTICE_POSTED_DATE) // postedDate와 subject는 필요하지 않음
val subject = intent.getStringExtra(NoticeWebActivity.NOTICE_SUBJECT)
navToNoticeActivity(it, articleId, category, postedDate, subject)
}
```
공지 웹뷰를 보여줄 때 필요한 데이터를 클래스로 선언하고, 필요없는 일부 매개변수는 제거하였습니다.
* e58a00f513702d1678a5df1a933387545f67b9a3: 공지 웹뷰를 보여주는 데 사용되는 `WebViewNotice`를 선언했습니다. 
* 8cfe273c205d880f13f5cc01a260cb3ba5b86538: 웹뷰에서 사용하지 않는 `postedDate`, `subject` 매개변수를 …
> kuring-46 공지 웹뷰 화면용 데이터 객체 생성

- app/src/main/java/com/ku_stacks/ku_ring/data/db/NoticeDao.kt
[Jira 티켓 링크](https://kuring.atlassian.net/browse/KURING-79?atlOrigin=eyJpIjoiOWViZjA0NWQwYzRkNDNhOWE1ZGJlMjI0YTkxNDgxYjUiLCJwIjoiaiJ9)
학과별 공지가 날짜 순서대로 보이지 않고 있습니다.
SQL 구문에 `postedDate` 내림차순 정렬 옵션을 추가하면 됩니다.
API base url을 다음의 주소로 바꿔야 합니다. 현재 DNS 문제로 https가 작동하지 않고 있어 IP로 접속해야 합니다.
```Kotlin
http://13.113.178.212:8080/api/
```
> kuring-79 [수정] 학과별 공지가 날짜의 내림차순으로 보이도록 수정

- app/src/main/java/com/ku_stacks/ku_ring/MyFireBaseMessagingService.kt
- app/src/main/java/com/ku_stacks/ku_ring/di/NavigatorModule.kt
- app/src/main/java/com/ku_stacks/ku_ring/navigator/KuringNavigator.kt
- app/src/main/java/com/ku_stacks/ku_ring/navigator/KuringNavigatorImpl.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/chat/ChatActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/feedback/FeedbackActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/MainActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/campus_onboarding/CampusFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/NoticesParentFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/category/NoticesChildFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/DepartmentNoticeFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/search/fragment_notice/SearchNoticeFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/setting/SettingFragment.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/my_notification/NotificationActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_storage/NoticeStorageActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeWebActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/notion/NotionViewActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/onboarding/OnboardingActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/splash/SplashActivity.kt
- app/src/main/java/com/ku_stacks/ku_ring/work/ReEngagementNotificationWork.kt
[Jira 티켓 링크](https://kuring.atlassian.net/browse/KURING-74?atlOrigin=eyJpIjoiNTgwOTczOTAxNTk2NDFlMmFiMDRkZjViZWJkYjY0ZmQiLCJwIjoiaiJ9)
`Activity`를 launch하는 코드가 앱 이곳저곳에 너무 광범위하게 퍼져 있어 모듈화에 큰 방해 요소가 되고 있습니다. 깔끔한 모듈화를 위해 화면 전환 코드를 한 곳으로 모아야 합니다.
https://github.com/ku-ring/KU-Ring-Android/pull/67/commits/f57e737677ec5f1e48028389993361516c6d8b42 PR에서 제시하신 대로, `Intent` 생성 및 화면 전환을 담당하는 `KuringNavigator` 인터페이스 및 구현체를 정의했습니다. 앞으로 모든 화면 전환은 `KuringNavigator`를 통해서만 이루어져야 합니다.
> kuring-74 화면 전환만을 담당하는 KuringNavigator 정의

- app/build.gradle
[Jira 티켓 링크](https://kuring.atlassian.net/browse/KURING-64?atlOrigin=eyJpIjoiMzE2NmE3MjQxYWM5NGYwNDhlZTczMDYyOWE3NTllMDUiLCJwIjoiaiJ9)
[Google Play 정책](https://developer.android.com/google/play/requirements/target-sdk)에 의해 2023년 8월 31일 이후에 게시되는 업데이트는 Android 13 이상을 target해야 합니다.
> Starting on August 31, 2023: App updates must target Android 13 or higher and adjust for behavioral changes in Android 13
따라서 현재 31인 target SDK를 33으로 상향했습니다. 공식 문서를 참고한 결과 target SDK를 상향해도 쿠링 앱에 미치는 영향은 없는 것으로 확인했습니다.
이 PR까지 누적된 변경사항을 출시할 예정입니다.
> kuring-64 Target SDK level을 33으로 상향

- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
- settings.gradle
[Jira 티켓 링크](https://kuring.atlassian.net/browse/KURING-69?atlOrigin=eyJpIjoiOGNhOWY0MjllNmM2NDA4ZWI1YWNmYWQ4MWZkMjhhYWIiLCJwIjoiaiJ9)
앱이 여러 모듈로 나눠져 있다면 각 모듈에서 의존성의 버전을 동일하게 맞춰야 하는데요, 지금처럼 라이브러리 버전을 하드코딩하면 버전을 관리하기가 매우 힘듭니다.
Gradle Version Catalog에 라이브러리를 선언하면 모든 모듈에서 같은 버전의 라이브러리를 사용할 수 있습니다. 
[Gradle - Sharing dependency versions between projects](https://docs.gradle.org/current/userguide/platforms.html)
> kuring-80 의존성을 Gradle Version Catalog에 선언

- app/build.gradle
- app/src/main/java/com/ku_stacks/ku_ring/ui/chat/ChatViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/feedback/FeedbackViewModel.kt
- app/src/main/java/com/ku_stacks/ku_ring/ui/main/search/SearchViewModel.kt
- app/src/test/java/com/ku_stacks/ku_ring/viewmodel_usecase/FeedbackViewModelTest.kt
- data/department/build.gradle
- data/department/src/main/java/com/ku_stacks/ku_ring/department/di/RepositoryModule.kt
- data/department/src/main/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepositoryImpl.kt
- data/notice/src/main/java/com/ku_stacks/ku_ring/notice/di/RepositoryModule.kt
- data/notice/src/main/java/com/ku_stacks/ku_ring/notice/repository/NoticeRepository.kt
- data/notice/src/main/java/com/ku_stacks/ku_ring/notice/repository/NoticeRepositoryImpl.kt
- data/notice/src/test/java/com/ku_stacks/ku_ring/notice/NoticeRepositoryTest.kt
- data/push/src/main/java/com/ku_stacks/ku_ring/push/di/RepositoryModule.kt
- data/staff/build.gradle
- data/staff/src/main/java/com/ku_stacks/ku_ring/staff/di/RepositoryModule.kt
- data/staff/src/main/java/com/ku_stacks/ku_ring/staff/repository/StaffRepository.kt
- data/staff/src/main/java/com/ku_stacks/ku_ring/staff/repository/StaffRepositoryImpl.kt
- data/user/build.gradle
- data/user/src/main/java/com/ku_stacks/ku_ring/user/di/RepositoryModule.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepository.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
현재 몇몇 `ViewModel`에서는 비즈니스 로직을 `...Client`에 접근하여 처리합니다. 그러나 모듈화된 쿠링 앱에서는 모든 비즈니스 로직 접근은 repository를 통해서만 가능합니다. `:feature` 모듈이나 `:app` 모듈에서는 테스트 코드 같은 예외적인 경우를 제외하면 `...Client`나 `...Service`에 접근해서는 안 됩니다. 
사실 테스트에서도 접근하지 않는 게 좋은데, 향후 테스트 코드 리팩토링 때 다시 살펴보겠습니다.
따라서 모든 비즈니스 및 데이터 로직은 각 도메인 객체별로 정의된 `...Repository` 클래스를 통해서만 처리하도록 수정했습니다. `Repository` 클래스가 없던 몇몇 모듈에 `Repository` 및 hilt 코드를 추가했고, `ViewModel`에서 `Repository`에만 접근하도록 객체 참조를 바꾸었습니다.
* https://github.com/ku-ring/KU-Ring-Android/commit/e9a514e8cdf230cc73dbb208ae726f0149d7d0ea, aa7693fd081fcdd0c4eb08af5d6de600e6b0146a, 1db639d233923a40d205809472f8b0f8bb1bcf4e: `UserRepository`에 피드백 전송 함수를 추가하고, `ChatViewModel`과 `FeedbackViewModel`에서 `FeedbackClient` 대신 `UserRepository`의 함수를 호출하도록 수정했습니다.
* fe57d015e52cbc15fa79c39f81ca6160faf5e7e0, …
> kuring-69 데이터 접근 경로를 repository로 일원화

- feature/feedback/src/test/java/com/ku_stacks/ku_ring/feedback/FeedbackViewModelTest.kt
- feature/feedback/src/test/java/com/ku_stacks/ku_ring/feedback/util/MainDispatcherRule.kt
kuring-101 작업의 연장선에서 FeedbackViewModelTest 가 fail 나는것을 수정합니다.
- FeedbackViewModelTest 수정
- Feedback Feature 모듈에 MainDispatcherRule 을 추가합니다. (테스트에 코루틴 dispatcher가 1개만 있도록 세팅해주는 rule)
testFixture 가 kotlin을 지원할수 있게 되면 MainDispatcherRule을 util 모듈로 이동합니다. (다른 방안으로는 test-util 모듈을 따로 만들거나 이 클래스만 util 모듈의 실제코드로 이동하여 해결하는것도 가능할듯 합니다)
> kuring-101 FeedbackViewModel unit test 수정, MainDispatcherRule 추가

- app/build.gradle
- common/preferences/build.gradle
- common/thirdparty/build.gradle
- common/ui_util/build.gradle
- common/util/build.gradle
- common/work/build.gradle
- data/department/build.gradle
- data/domain/build.gradle
- data/local/build.gradle
- data/notice/build.gradle
- data/push/build.gradle
- data/remote/build.gradle
- data/staff/build.gradle
- data/user/build.gradle
- feature/edit_subscription/build.gradle
- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/compose/Subscriptions.kt
- feature/feedback/build.gradle
- feature/my_notification/build.gradle
- feature/notice_storage/build.gradle
- gradle/libs.versions.toml
https://kuring.atlassian.net/browse/KURING-122
- compose에서는 textField 에 요상한 버그가 있어서 수정합니다 (View의 EditText가 벌써부터 그리워지네요😫)
- 사용자가 텍스트 중간에 한글을 입력하려 하면 커서가 맨뒤로 가지는 이슈(영어는 이슈 재현안됨)
- 관련 [Issue Tracker 링크](https://issuetracker.google.com/issues/195231205?source=post_page-----5866bdae33e7--------------------------------)
- 피드백 화면 뿐만 아니라 검색화면에서도 지장이 있어, 사용자에게 안좋은 경험을 줄 수 있어 라이브러리 업데이트를 진행했습니다.
- 각 모듈별 compileSdk, targetSdk, minSdk 를 Gradle Version Catalog에 의존하도록 합니다
- compose-bom 을 2024.01.00 으로 업데이트합니다. 이 과정에서 아래의 추가 업데이트/대응이 필요
- targetSdk를 34로 업데이트
- Subscriptions.kt 에서 HorizontalPager 사용처 업데이트 대응 [84cd311](https://github.com/ku-ring/KU-Ring-Android/pull/89/commits/84cd3119ae68219a408e285d275b9917af14f069)
https://github.com/ku-ring/KU-Ring-Android/assets/45001093/af5b47fa-1fa9-4fb4-808c-3cb0ab …
> kuring-122 compose 키보드 이슈 업데이트 및 모듈간 sdk 의존성 통합

- common/util/src/main/java/com/ku_stacks/ku_ring/util/DateUtil.kt
https://kuring.atlassian.net/browse/KURING-123
CI 과정에서 `DateUtilTest`가 간헐적으로 실패하는 문제가 있었습니다. 해당 테스트는 두 `java.util.Calendar` 객체 간의 epoch의 차이를 계산하는 테스트입니다.
`DateUtil.getCalendar()` 함수에서 대부분의 필드를 주어진 값으로 설정하지만, `Calendar.MILLISECOND` 필드는 설정하지 않고 있었습니다. 따라서 `getCalendar()` 함수에서 `Calendar` 객체를 만들 때 MILLISECOND 필드를 0으로 설정하도록 수정했습니다.
> kuring-123 [수정] DateUtilTest가 간헐적으로 실패하던 문제 해결

- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/EditSubscriptionActivity.kt
- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/compose/EditSubscriptionScreen.kt
https://kuring.atlassian.net/browse/KURING-125?atlOrigin=eyJpIjoiMTRkMzQwNzk0YjBiNDhiZTlkYzQ5NjY4NmYxMzgwNzciLCJwIjoiaiJ9
최상위 composable 네이밍 컨벤션에 맞지 않는 이름을 수정했습니다.
Feature 모듈의 최상위 composable 네이밍 컨벤션을 다음과 같이 정했습니다.
1. 모듈 이름을 camel case로 적은 문자열 뒤에
2. `Screen`을 접미사로 붙입니다.
예를 들어, `:feature:edit_departments` 모듈의 최상위 composable은 `EditDepartmentsScreen`으로 명명되어야 합니다.
* 649f682caf4c22ae211a32e483035d794a7b9da9: `edit_subscription` 모듈의 최상위 composable인 `Subscriptions`의 이름을  `EditSubscriptionScreen`으로 수정했습니다. 
나머지 모듈은 이미 컨벤션을 잘 지키고 있어 수정하지 않았습니다.
> kuring-125 [수정] 알림 구독 화면의 최상위 composable 이름을 컨벤션에 맞게 수정

- data/notice/src/main/java/com/ku_stacks/ku_ring/notice/mapper/ResponseToEntity.kt
https://kuring.atlassian.net/browse/KURING-136?atlOrigin=eyJpIjoiNWRiZGZmYTRjZmRiNGQyY2FkNDQyN2NiNDAyOGZiNjEiLCJwIjoiaiJ9
학교 홈페이지가 업데이트되면서, 서버에서 내려주는 학과별 공지의 날짜 포맷이 바뀌었습니다.
* 기존: `yyyy-MM-dd`
* 현재: `yyyy.MM.dd`
현재 학사 공지에서는 `yyyy.MM.dd` 포맷으로 보여주고 있으므로, 학과별 공지에서도 서버에서 내려주는 형식 그대로 보여주면 됩니다.
추후 형식이 바뀌면 다시 수정할 예정입니다.
이 PR은 즉시 출시해야 할 것 같습니다. 만약 현재 `develop`을 출시한다면, 이 PR 외에 함께 출시되는 PR은 다음과 같습니다.
* v2 `:common:designsystem` 리소스
* 앱 모듈화 (일부)
2.0 UI가 함께 출시되지는 않으므로, develop 브랜치를 즉시 출시해도 문제가 없다고 판단했습니다. PR 확인하시는 대로 즉시 출시할게요.
> kuring-136 바뀐 학과별 공지 날짜 포맷 대응

- .idea/compiler.xml
- .idea/kotlinc.xml
- app/proguard-rules.pro
https://kuring.atlassian.net/browse/KURING-139?atlOrigin=eyJpIjoiMzBjMzViM2JjYmE1NGU0ZmE2MjE4YWY5NWI2ZWRkY2EiLCJwIjoiaiJ9
1.3.6 버전에서, 온보딩 화면에서 `공지 알림 설정하기` 화면을 누르면 앱이 강제 종료되는 문제가 있습니다.
```
Unable to create call adapter for class kc.o
```
난독화 해제하고 확인해 보니, RxJava에서 발생하는 문제였습니다.
```
java.lang.IllegalArgumentException: Unable to create call adapter for class io.reactivex.rxjava3.core.Single
```
Retrofit에서 사용하는 request, response 클래스는 난독화로부터 보호되어야 합니다. 따라서 지금까지는 다음과 같이 `proguard-rules.pro` 파일에 보호 규칙을 작성하고 있었습니다.
```
-keep class com.ku_stacks.ku_ring.data.api.request.** { *; }
-keep class com.ku_stacks.ku_ring.data.api.response.** { *; }
-keep class com.ku_stacks.ku_ring.data.db.** { *; }
-keep class com.ku_stacks.ku_ring.data.model.** { *; }
-keep class …
```
> kuring-139 [수정] 난독화 보호 경로 수정

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/CenterTitleTopBar.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/NoticeItem.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/theme/Color.kt
- common/ui_util/src/main/java/com/ku_stacks/ku_ring/ui_util/preview_data/Notice.kt
- feature/notice_storage/build.gradle
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/NoticeStorageAdapter.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/SavedNoticeViewHolder.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/NoticeStorageScreen.kt
- feature/notice_storage/src/main/res/values/string.xml
https://kuring.atlassian.net/browse/KURING-102?atlOrigin=eyJpIjoiNjg2ODUyMGFkOWNiNDMyMjhmY2QyYjQyY2NhZGRjODIiLCJwIjoiaiJ9
공지 보관함 화면의 메인 UI를 구현하였습니다.
* 삭제 alert 구현
* ViewModel 로직 구현
* Activity와 연결
현재 `화면 삭제` 버튼이 보일 때 bottom navigation이 보이지 않도록 디자인되어 있습니다. 이건 나중에 bottom navigation을 compose로 구현할 때 작업할 예정입니다.
> kuring-102 공지 보관함 UI 구현 (1)

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/theme/Color.kt
- feature/onboarding/build.gradle
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/OnboardingActivity.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/OnboardingScreen.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/OnboardingScreenDestinations.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/inner_screen/ConfirmDepartment.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/inner_screen/FeatureTabs.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/inner_screen/OnboardingComplete.kt
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/inner_screen/SetDepartment.kt
- gradle/libs.versions.toml
https://kuring.atlassian.net/browse/KURING-41?atlOrigin=eyJpIjoiNzVmZjE3ZDM0YmNjNGY2ZGEyZGQ4M2U4NWNiMWFiYWEiLCJwIjoiaiJ9
온보딩 화면의 composable 구조를 정의했습니다. 이번 PR은 이전과 다르게 구조를 먼저 만든 후, 개별 UI를 구현합니다.
`OnboardingScreen`에서 compose navigation을 사용했는데, 궁금하신 점이 있으면 코멘트로 남겨주세요.
* 온보딩 UI 구현
* 온보딩 비즈니스 로직 구현 (`ViewModel` 등)
* `ViewModel`은 아마 `OnboardingScreen` 전체를 대상으로 만들 것 같습니다. UI끼리 공유해야 할 데이터가 몇 개 있기도 하고(선택한 학과 등), 로직이 많지는 않아서 그냥 하나로 합칠까 생각하고 있어요
> kuring-41 온보딩 composable 구조 완성

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/KuringAlertDialog.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/theme/Color.kt
- feature/edit_departments/src/main/java/com/ku_stacks/ku_ring/edit_departments/compose/EditDepartmentsPopup.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/NoticeStorageActivity.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/NoticeStorageViewModel.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/NoticeStorageScreen.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/components/DeleteSelectedNoticesAlertDialog.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/components/NoticeSelectionStateImage.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/components/NoticeStorageTopBar.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/components/StoredNotice.kt
- feature/notice_storage/src/main/java/com/ku_stacks/ku_ring/notice_storage/compose/components/StoredNotices.kt
- feature/notice_storage/src/main/res/values/string.xml
https://kuring.atlassian.net/browse/KURING-102?atlOrigin=eyJpIjoiNDUyYTYzM2Q1NjMyNGQ2MjlmY2Q4NzViMTE1ODI1NGUiLCJwIjoiaiJ9
* 공지 보관함 로직을 구현했습니다. 기존 ViewModel 코드를 일부 재활용하고, 바뀐 UI에 맞는 로직을 추가했습니다.
* 68ea71448cc02c558853cf58367c741bf54d3276: 일부 디자인 변경점을 적용했습니다.
* acc64a918c0f95bb8e304f2162e37226f39c9ce0: `:common:designsystem` 중 `KuringAlertDialog`의 오버로딩을 추가했습니다. Dialog를 단순히 무시할 때와(dismiss) 작업을 아예 취소할 때(cancel) 실행할 작업이 같은지 다른지에 따라 오버로딩이 나뉘게 됩니다.
입니다! 다른 화면도 계속 작업중입니다.
> kuring-102 공지 보관함 로직 구현

- common/util/src/main/java/com/ku_stacks/ku_ring/util/DateUtil.kt
https://kuring.atlassian.net/browse/KURING-145?atlOrigin=eyJpIjoiN2UzZGM4NGU5MWJkNDQ0NjhhZGRjOWQxNjZlOWZhMWYiLCJwIjoiaiJ9
일부 공지의 날짜 형식을 파싱할 때 에러가 발생하고 있습니다. 새로 배포된 서버에서 보내주는 날짜 형식이 바뀌었기 때문입니다.
* 기존: `yyyyMMdd`
* 현재: `yyyy.MM.dd`
2.0부터는 에러가 발생하는 해당 코드를 사용하지 않으므로, try catch를 통해 `ParseException`이 발생하면 원본 문자열을 돌려주도록 임시로 대처했습니다.
이 PR은 머지되는 즉시 출시될 예정입니다.
> kuring-145 [수정] 서버에서 내려주는 새 날짜 형식에 대응 (yyyy.MM.dd)

- common/thirdparty/build.gradle
- common/thirdparty/src/main/java/com/ku_stacks/ku_ring/thirdparty/firebase/MyFireBaseMessagingService.kt
- common/util/build.gradle
- common/util/src/main/java/com/ku_stacks/ku_ring/util/KuringNotificationManager.kt
- common/work/build.gradle
- common/work/src/main/java/com/ku_stacks/ku_ring/work/ReEngagementNotificationWork.kt
- common/work/src/main/java/com/ku_stacks/ku_ring/work/RegisterUserWork.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserClient.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserService.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/di/UserModule.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/request/RegisterUserRequest.kt
- data/remote/src/test/java/com/ku_stacks/ku_ring/remote/UserServiceTest.kt
- data/user/build.gradle
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepository.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
- feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
https://kuring.atlassian.net/browse/KURING-41?atlOrigin=eyJpIjoiNjJlYWM4ZjliNjk2NGNlN2E4ZTVlYmU3NDZjNDBmMGYiLCJwIjoiaiJ9
* v2 사용자 등록 API를 추가하고, 새 FCM 토큰을 받았을 때 사용자 등록 API를 호출합니다. 온보딩 task에서 구현한 이유는, fcm 토큰을 받는 시기가 대략 온보딩 화면에 있을 때이기 때문입니다.
* 알림을 보내는 코드를 `:common:util` 모듈로 옮겼습니다.
> kuring-41 사용자 등록 API 추가

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/CenterTitleTopBar.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/theme/Color.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingFragment.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingScreen.kt
- feature/main/src/main/res/layout/fragment_setting.xml
https://kuring.atlassian.net/browse/KURING-100?atlOrigin=eyJpIjoiMTFlNjU2Y2MzOTM1NGU5YWFmNGQzOTZjMTQzM2VhODEiLCJwIjoiaiJ9
`SettingFragment`와 `SettingScreen`을 연결하고, 사용하지 않는 코드를 제거했습니다.
이제 bottom navigation만 하면 화면 구현은 끝납니다. 
하지만 다크 모드가 남아있...
> kuring-100 설정 화면을 Fragment와 연결

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/CenterTitleTopBar.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/theme/Color.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingFragment.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingViewModel.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingScreen.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/components/ChevronIcon.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/groups/FeedbackGroup.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/groups/InformationGroup.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/groups/SocialNetworkServiceGroup.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/groups/SubscribeGroup.kt
- feature/main/src/main/res/layout/fragment_setting.xml
https://kuring.atlassian.net/browse/KURING-100?atlOrigin=eyJpIjoiMTFlNjU2Y2MzOTM1NGU5YWFmNGQzOTZjMTQzM2VhODEiLCJwIjoiaiJ9
1. 더보기 화면에 있는 각 그룹을 구현했습니다. 아래 사진에서 빨간색 네모 친 부분을 하나의 그룹으로 보았습니다.
2. `ViewModel` 로직을 구현했습니다. 사실 로직이랄 게 딱히 없습니다.
* Compose와 Fragment 연결
* 사용하지 않는 코드 제거
> kuring-100 더보기 화면의 각 그룹 및 로직 정의

- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingFragment.kt
- feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-151?atlOrigin=eyJpIjoiYjc2ZmMxNjkxYWE2NDdmYThiOTQwYjYxYzRjYjljN2UiLCJwIjoiaiJ9
설정 화면의 `인스타그램` 항목을 터치하면 쿠링 인스타그램 계정으로 이동하는 코드를 추가했습니다. 앱이 있으면 앱으로 열고, 앱이 없으면 웹 페이지로 엽니다.
에뮬레이터로 실행한 결과입니다. 인스타그램 앱이 없어서 웹으로 연 모습입니다.
아이콘 점검만 하면 끝. 이건 내일 할게요
> kuring-151 쿠링 인스타그램 탐색 링크 추가

- gradle/libs.versions.toml
> Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
Gradle dependencies 확인 결과 DataBinding과 `kotlinx-coroutines`의 이슈라고 추정했고, AGP(DataBinding)를 8.0.0에서 8.1.4로, `kotlinx-coroutines`를 1.6.4에서 1.7.3으로 업데이트했습니다. 
저 버전을 선택한 이유는, 두 버전 모두 Kotlin 1.8.x에 의존하는 가장 최신 버전이었기 때문입니다. AGP 8.2.0와 `kotlinx-coroutines` 1.8.0 이후 버전에서는 Kotlin 1.9.x에 의존합니다.
> [수정] assembleRelease 오류 해결

- common/util/build.gradle
- common/util/src/testFixtures/java/com/ku_stacks/ku_ring/util/TestingLiveDataExt.java
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle
- 우선 이미 셧다운된 jcenter는 레포지터리 프로바이더 목록에서 제외했습니다.
- 다음과 같이 gradle 패러미터 변경했습니다.
- JVM Heap 사이즈 4기가로 올렸습니다.
- 병렬 빌드 옵션 켰습니다.
- 데몬 프로세스 켰습니다. 데몬 프로세스의 메모리 상에 빌드 결과물 보관할 수 있어서 다음 빌드에서 시간을 줄일 수 있습니다.
- Jetifier 껐습니다. 해당 옵션 꺼야 [빌드 5~8% 한번에 빨라진다고](https://pluu.github.io/blog/android/io22/2022/05/20/io22-whats-new-in-android-development-tools/) 합니다.
> [2.0/fix-gradle-properties] 빌드 속도 향상을 위한 gradle.properties 개선

- .github/workflows/auto-delete-merged-branches.yml
- [phpdocker-io/github-actions-delete-abandoned-branches@v1](https://github.com/phpdocker-io/github-actions-delete-abandoned-branches)을 활용하여 60일동안 커밋 기록 없는 브랜치는 자동 삭제합니다.
- 매주 월요일 7시 45분에 해당 액션 돌아감
- workflow_dispatch 활용해서 수동으로 돌릴 때 dry_run: yes 설정하면 삭제할 수 있는 브랜치만 볼 수 있음
> [2.0/delete-redundant-braches] 60일동안 커밋 없는 브랜치 자동삭제 스크립트 제작

- app/build.gradle
- data/remote/build.gradle
https://kuring.atlassian.net/browse/KURING-140?atlOrigin=eyJpIjoiMjQwNDNhMjcxM2FjNDNmMGFlZWYwOTBkYWExNzI2ZTUiLCJwIjoiaiJ9
서버 인스턴스 위치가 다음과 같이 변경되었습니다.
* 기존 테스트 서버: 폐쇄 예정
* 기존 프로덕션 서버(헤로쿠): 테스트 서버로 변경
* 새 프로덕션 서버 신설
* `develop`을 `release`에 머지한 후 출시
* `develop`을 `2.0/base`에 머지
> kuring-140 테스트, 프로덕션 서버 URL을 바뀐 URL로 수정

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/NoticeItem.kt
https://kuring.atlassian.net/browse/KURING-158?atlOrigin=eyJpIjoiMzgwYTRhNmMwYmRiNDRhMTkwNjFkYTZlOGNjYmY3NjkiLCJwIjoiaiJ9
왜인지는 모르겠으나, 공지 제목이 1줄일 때에도 2줄 높이로 보여주고 있던 문제를 해결했습니다.
(before - after)
이제 칼 들고 협박해도 더 안함
출시합시다
> kuring-158 공지 제목이 1줄일 때, 2줄 높이로 보여주지 않도록 수정

- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/ApplicationPlugin.kt
- Databinding 생성된 클래스가 안 잡히는 이슈 포착
- [Reference](https://work2type.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-Didnt-find-class-androidxdatabindingDataBinderMapperImpl-on-path-%EC%98%A4%EB%A5%98)
> Apply databinding enabled in app module

- app/build.gradle.kts
- app/src/main/java/com/ku_stacks/ku_ring/KuRingApplication.kt
디버그 앱에서 발생한 오류가 release에서 발생한 것처럼 crashlytics에 잡히는 문제가 있어, debug 앱에서는 아예 crashlytics 감지를 끄도록 설정했습니다.
`KuringApplication.onCreate()`에서 디버그 앱이라면 crashlytics를 끕니다.
ref: https://stackoverflow.com/questions/62402856/new-firebase-crashlytics-disable-in-debug-mode
> Debug 앱에서는 crashlytics를 끔

- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/KuringWebView.kt
- common/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/topbar/CenterTitleTopBar.kt
- feature/notice_detail/build.gradle.kts
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebActivity.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebScreen.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebViewModel.kt
- feature/notice_detail/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-167?atlOrigin=eyJpIjoiMmMwYWQwNGQ1ZTdiNDhkZGEwOWYwZTljZDg2MDQzZDEiLCJwIjoiaiJ9
공지 웹뷰 페이지를 compose로 migrate했습니다. `Activity::finish` 등 최소한의 코드를 제외하고 모두 compose로 옮겼습니다.
| Before | After |
| --- | --- |
| ![old](https://github.com/ku-ring/KU-Ring-Android/assets/45386920/ef2bbff3-ab03-4b2e-b10e-b3ed1be655c8) | ![new](https://github.com/ku-ring/KU-Ring-Android/assets/45386920/282e3f6c-1d05-4e5c-a16a-a419be40da7c) |
* 65eca094235a7bd0a106fdd0b330929b4f2fbbfc: Compose 프리뷰에서는 android view를 지원하지 않아, `KuringWebView`를 포함하는 composable 전체를 프리뷰에서 볼 수 없는 문제가 있었습니다. 이에 프리뷰에서는 웹뷰 대신 항상 `KuringWebViewErrorPage`를 보여주도록 수정했습니다.
* 055996cad9c516e9a4a02df39855f7c902ea30f3: 공지 웹뷰 레이아웃을 compose로 migrate한 `NoticeWebScreen`을 구현했습니다.
* …
> kuring-167 공지 웹뷰 페이지를 compose로 migrate

- app/src/main/java/com/ku_stacks/ku_ring/navigator/KuringNavigatorImpl.kt
- common/ui_util/src/main/java/com/ku_stacks/ku_ring/ui_util/KuringNavigator.kt
- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/EditSubscriptionActivity.kt
- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/EditSubscriptionViewModel.kt
- feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/compose/EditSubscriptionScreen.kt
https://kuring.atlassian.net/browse/KURING-169
`:feature:edit_notification` 모듈을 compose로 migrate했습니다. 사실 UI 자체는 전부 compose로 작성되어 있었고, Activity에 남아있던 로직을 compose로 옮기는 등 리팩토링 작업을 주로 수행했습니다.
UI 변경사항이 없는 관계로 스크린샷은 첨부하지 않았습니다.
* 5bb0775a94999a11bf8821bfffdcc58a398208d5: 구독 수정 화면에서 view 코드를 제거하고, Activity에 남아있던 로직을 모두 compose로 옮겼습니다.
* 69cf804f260e6a8b7ba821301b3a12bf203ec498: `EditSubscriptionViewModel`에서 사용되지 않는 변수를 제거했습니다. 구독 수정 화면이 온보딩 과정에서 사용자에게 보이지 않게 되어, `isFirstRun` 변수를 사용할 필요가 없어졌습니다.
* ef2913c20c329320e3a5b832aa99fd64a55e14c1: `KuringNavigator`에서 `isFirstRun` 변수 제거
> kuring-169 공지 구독 화면을 compose로 migrate

- .github/workflows/android-release.yml
`release` 브랜치를 없애고, 대신 `release/{x.y.z}` 브랜치에서 릴리스 액션이 실행되도록 수정했습니다.
> 릴리스 액션 실행 조건 변경

- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/ApplicationPlugin.kt
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/ViewBasedFeaturePlugin.kt
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/dsl/GradleDsl.kt
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/primitive/HiltPlugin.kt
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/primitive/RoomPlugin.kt
- build.gradle.kts
- gradle/libs.versions.toml
https://kuring.atlassian.net/browse/KURING-174?atlOrigin=eyJpIjoiNjEyYjEzNDY5OTgwNGJiZTg2ODQyZDZlMmFlMDhkY2MiLCJwIjoiaiJ9
Kotlin 2.0 이후에는 kapt는 더 이상 업데이트되지 않고, 대신 ksp를 사용하는 것이 좋습니다. 따라서 쿠링 앱에서도 kapt를 ksp로 migrate했습니다. 
Room, Hilt 등 대부분의 라이브러리는 이미 ksp를 지원하지만, view binding은 여전히 kapt를 사용하고 있으며 ksp를 지원할 계획도 없다고 합니다. 
이 때문에 kapt를 완전히 제거하지는 못했고, 따라서 빌드 시간 향상도 예상보다 크지 않았습니다(49초 → 42초). View를 완전히 제거한 후에는 빌드 시간이 크게 향상될 것으로 예상합니다. 실제로 빌드 돌려보면 `kapt...` 작업에서 잠깐 버벅이는 느낌이 있습니다.
* 8194b44775286c9630b0e6487958eb6b7b158a72: 의존성을 선언할 때 사용하는 `kapt()`, `kaptTest()` 등은 모두 ksp로 교체했습니다.
* c4a504956913e90ae6a363b69ac4140207db2621: 다만 상술했듯이 view 코드에서 kapt를 요구하는 경우가 있어, `ApplicationPlugin`과 `ViewBasedFeaturePlugin`에 kapt를 선언했습니다.
> kuring-174 kapt를 ksp로 migrate

- common/ui_util/src/main/java/com/ku_stacks/ku_ring/ui_util/KuringRoute.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreenRoute.kt
https://kuring.atlassian.net/browse/KURING-168?atlOrigin=eyJpIjoiYTkwNjg2MGEwN2RkNDkyYWIzMjA4YjEzNjhjNzg4MzciLCJwIjoiaiJ9
메인 화면 navigation migration 작업을 재개하였습니다. 구체적으로 말씀드리면, 설정 탭을 compose + type-safe navigation으로 migrate하는 중입니다.
작업에 앞서 현우님이 #235 에서 정의하셨던 route 코드를 인터페이스로 분리했습니다. 나중에 다른 화면에서도 사용할 수 있을 것 같아 `:common:ui_util` 모듈에 정의했습니다.
* c8b66746b27ec796454e2290bc9011190b4dab84: `KuringRoute` 인터페이스 분리
> refactor: Type-safe navigation route용 KuringRoute를 인터페이스로 분리

- feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreen.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/NoticeCompositionLocalProvider.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/NoticeScreen.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/components/KuringBotFab.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/components/KuringBotFabState.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/DepartmentNoticeScreen.kt
https://kuring.atlassian.net/browse/KURING-205?atlOrigin=eyJpIjoiYmEyZDJhMjBkYWNhNDAxMTlhYzkyNTc1NTIyM2RhYjgiLCJwIjoiaiJ9
1. 쿠링봇 버튼이 모든 탭에서 보이는 문제가 있습니다. 공지 탭에서만 보이도록 수정해야 합니다.
2. 쿠링봇이 학과 선택 바텀시트를 가리는 문제가 있습니다.
쿠링봇 버튼이 공지 탭에서만 보이도록 수정했습니다.
학과 선택 bottom sheet가 열려 있을 때에는 쿠링봇 버튼이 보이지 않습니다. 
쿠링봇 버튼의 상태를 관리하는 `KuringBotFabState`를 정의하고, Composition local을 통해 state 객체를 내려보냅니다. 학과 선택 bottom sheet에서 시트를 열고 닫을 때 `KuringBotFabState`의 `hide()` 또는 `show()` 함수를 실행합니다.
https://github.com/user-attachments/assets/7ecc388e-3951-47da-a5a6-1992973627fb
향후에는 화면 구조를 수정하여 쿠링봇 버튼과 학과 선택 시트가 같은 hierarchy에 오도록 수정하여, 버튼과 바텀시트가 서로를 직접 참조할 수 있도록 수정할 예정입니다.
> kuring-205 쿠링봇 fab 오류 수정

- feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreenNavigationBar.kt
이미 선택된 탭이 여러번 다시 눌릴수 있어 의도치않게 동작합니다
간단하게 현재 보는 탭이 아닐경우에만 바텀탭이 선택되도록 하였습니다
> fix: Prevent multiple selection of the same tab

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/LazyNoticeItemColumn.kt
- data/department/src/main/java/com/ku_stacks/ku_ring/department/UnsupportedDepartmentUtil.kt
- data/department/src/main/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepositoryImpl.kt
- data/department/src/test/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepositoryTest.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/DepartmentNoticeScreen.kt
- feature/main/src/main/res/values/strings.xml
- feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/OnboardingViewModel.kt
- feature/splash/build.gradle.kts
- feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
- feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
- feature/splash/src/test/java/com/ku_stacks/ku_ring/splash/SplashViewModelTest.kt
https://kuring.atlassian.net/browse/KURING-202?atlOrigin=eyJpIjoiYTc4NTI3MTVhNDhjNDNmY2FhYTUwY2EwYWJmNjBkZWQiLCJwIjoiaiJ9
공지를 볼 수 없는 커뮤니케이션디자인학과를 앱에 추가해야 하는데, `지원하지 않는 학과`로 추상화하여 작업했습니다.
* 서버로부터 학과를 갱신할 때, 지원하지 않는 학과도 업데이트
* 지원하지 않는 학과의 공지 리스트 UI 추가
* 그 외 자잘한 기능 수정
> kuring-208 지원하지 않는 학과 추가

- feature/kuringbot/src/main/java/com/ku_stacks/ku_ring/kuringbot/compose/KuringBotScreen.kt
https://kuring.atlassian.net/browse/KURING-211?atlOrigin=eyJpIjoiN2Q1NWRjMDJiYjVlNGQ2YzhlNDViZWEwMGJlNGE3ZDkiLCJwIjoiaiJ9
Compose `Text`는 기본적으로 텍스트 선택을 허용하지 않습니다. 그런데 디자인팀에서 텍스트가 선택 가능하도록 수정할 것을 요청하셔서, `SelectionContainer`를 사용하여 메시지 단위로 텍스트를 선택할 수 있도록 수정했습니다.
처음에는 선택 scope를 전체 메시지로 넓히려고 했습니다. 즉 `KuringBotMessages`를 `SelectionContainer`로 감싸는 것입니다.
그런데 메시지 전체를 감싸면 알 수 없는 이유로 `Column` weight가 깨집니다(스샷 참고). 그래서 전체 메시지가 아닌 개별 메시지 단위로 선택할 수 있도록 구현했습니다.
> kuring-211 쿠링봇 질문/응답 텍스트를 선택할 수 있도록 수정

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/DepartmentItems.kt
https://kuring.atlassian.net/browse/KURING-210?atlOrigin=eyJpIjoiZDI3YmQyZWI2MjZjNDkyZTk5NDhlOGU2YzVjNGExMTQiLCJwIjoiaiJ9
자잘하게 많네요 ㅋㅋ
학과 선택 화면에서는 학과 아이템의 오른쪽 아이콘 부분만 clickable한데, 사용자 소통 결과 학과 이름을 클릭했을 때에도 콜백이 작동하게 해달라는 의견이 있었습니다. ([8/21 회의록](https://www.notion.so/kuring/bd050427d7884c56a3e2bfda615f2945?pvs=4#37e1cfd034924f1f94dd795dd89b4764) 참고)
따라서 학과 아이템 전체를 클릭 가능하도록 수정했습니다. 단, 학과를 삭제할 때에는 아이템 전체가 아닌 `삭제` 버튼을 클릭해야만 삭제되도록 했습니다.
> kuring-210 학과 클릭 영역을 넓힘

- feature/kuringbot/src/main/java/com/ku_stacks/ku_ring/kuringbot/compose/components/KuringBotTextField.kt
https://kuring.atlassian.net/browse/KURING-219?atlOrigin=eyJpIjoiMWI2MzAxZTNjYjE4NDdmYjhlYTQxYjdjNTc4YmQyNTMiLCJwIjoiaiJ9
쿠링봇 `TextField`의 커서 색깔이 검은색으로 고정되어 있어, 다크 모드에서 커서가 잘 보이지 않는 문제가 있었습니다.
따라서 커서 색을 텍스트 색과 동일하게 수정했습니다.
_솔직히 이건 머티리얼 잘못인듯_
> kuring-219 다크 모드에서 커서의 시인성 향상

- core/util/build.gradle.kts
https://kuring.atlassian.net/browse/KURING-220?atlOrigin=eyJpIjoiNjk1OThkODFiNDc3NGVlMmEzYjVmMjg2MjI3NDcxNGIiLCJwIjoiaiJ9
#349 에서 미처 제거하지 못한 build config 필드를 제거합니다. 석준님 환경에서 정상 빌드되는 것 확인했습니다.
> gradle: 제거되지 않은 build config 제거

- .github/workflows/android-develop.yml
- .github/workflows/android-release.yml
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/FeaturePlugin.kt
- 안드로이드 클린빌드시 unit test, android test 모두 돌아가는 것을 파악
- CI 빌드가 아닌 로컬빌드에서 test 태스크는 건너뛰게 설정
결과
- 기존 클린빌드 시간 65초대에서 55초로 줄임
> 빌드시 테스트 태스크 제외시키고 CI에서만 돌리기

- .github/workflows/android-develop.yml
- .github/workflows/android-release.yml
- build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/FeaturePlugin.kt
#362 의 원래 목적은 클린 빌드 시에만 테스트 코드를 실행하지 않는 것이었으나, PR 적용 후 github actions를 제외한 모든 곳에서 테스트가 돌지 않고 있습니다. (정확히는 `-PisCI=true` 파라미터를 추가해야만 돔)
따라서 일단 #362 를 revert하고, 향후 클린 빌드만 타겟할 수 있는 방법을 찾으면 다시 고민해 봅시다.
> 클린 빌드 시에도 테스트 코드를 실행하도록 수정

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropState.kt
- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DragDropUtil.kt
- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DraggableItem.kt
- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DraggableLazyColumn.kt
- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/dragdrop/DraggableLazyColumnItem.kt
- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/CategoryOrder.kt
- data/local/src/main/java/com/ku_stacks/ku_ring/local/di/DBModule.kt
- data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/CategoryOrderEntity.kt
- data/local/src/main/java/com/ku_stacks/ku_ring/local/room/CategoryOrderDao.kt
- data/local/src/main/java/com/ku_stacks/ku_ring/local/room/KuRingDatabase.kt
- data/user/build.gradle.kts
- data/user/src/main/java/com/ku_stacks/ku_ring/user/mapper/DomainToEntity.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/mapper/EntityToDomain.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepository.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
https://kuring.atlassian.net/browse/KURING-227?atlOrigin=eyJpIjoiODliNjhlODc0ZGRiNDJmZTgyY2M3MTA5NzUwNzVmYzUiLCJwIjoiaiJ9
카테고리 순서 변경의 첫 번째 작업으로, 드래그 가능한 리스트 `DraggableLazyColumn`과 카테고리 순서 DB를 구현했습니다.
* `DraggableLazyColumn`은 [여기](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation/integration-tests/foundation-demos/src/main/java/androidx/compose/foundation/demos/LazyColumnDragAndDropDemo.kt)을 많이 참고했습니다. 코드를 자세히 보기는 조금 어려울 수도 있습니다. 프리뷰를 참고하여 보시면 됩니다.
* 카테고리 순서 DB는 entity 정의, Dao 정의, 도메인 객체 추가, `UserRepository`에 기능 노출 순서대로 구현되어 있습니다. 매우 전형적인 흐름이므로 리뷰하시기 한결 쉬울 것 같습니다.
> kuring-227 드래그 LazyList, 카테고리 순서 DB 구현

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/comment/Comment.kt
- core/designsystem/src/main/res/drawable/ic_message_circle_v2.xml
- core/designsystem/src/main/res/drawable/ic_reply_v2.xml
- core/designsystem/src/main/res/drawable/ic_user_v2.xml
- core/designsystem/src/main/res/values/strings.xml
- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/NoticeComment.kt
- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/PlainNoticeComment.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/CommentsBottomSheet.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/LazyPagingCommentColumn.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/PreviewData.kt
- feature/notice_detail/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-230?atlOrigin=eyJpIjoiM2VhMDVjMmQxNmQ3NDcxZGI1YWJhMTU4ZmRhOWI1N2IiLCJwIjoiaiJ9
공지 댓글 UI 컴포넌트를 추가했습니다.
공지 아이템, 대댓글 아이템, 바텀시트까지 작업했습니다. 데이터 로직 연결은 다음 PR에서 진행합니다.
> kuring-230 공지 댓글 UI 추가

- data/department/src/main/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepositoryImpl.kt
https://kuring.atlassian.net/browse/KURING-236?atlOrigin=eyJpIjoiNDRjNjNkNDkyZDk1NDZhNWExOGMxZjVmOGZmOWRjMjEiLCJwIjoiaiJ9
DB에 새 학과를 넣지 않던 문제를 해결했습니다. 
학과 테이블의 key인 `name`을 비교하여, 로컬 DB에 `name`이 없는 entry를 추가하는 방식으로 구현했습니다.
새 학과인 `KU자율전공학부`가 정상 추가되었고, 테이블의 다른 row에는 영향이 없음을 확인했습니다.
**이 PR은 merge 즉시 출시되어야 합니다.**
> kuring-236 새 학과를 앱에서 볼 수 없던 문제 해결

- core/designsystem/src/main/res/drawable/ic_preview_close_v2.xml
- core/designsystem/src/main/res/drawable/ic_preview_open_v2.xml
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserClient.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserService.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/util/HeaderInterceptor.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/verification/VerificationClient.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/verification/VerificationService.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
- data/verification/src/main/java/com/ku_stacks/ku_ring/verification/repository/VerificationRepository.kt
- data/verification/src/main/java/com/ku_stacks/ku_ring/verification/repository/VerificationRepositoryImpl.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/CodeInputGroup.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/EmailInputGroup.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/PasswordInputGroup.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordNavigation.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordViewModel.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/inner_screen/EmailVerificationScreen.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signup/SignUpViewModel.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signup/inner_screen/EmailVerificationScreen.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/state/VerifiedState.kt
https://kuring.atlassian.net/browse/KURING-235?atlOrigin=eyJpIjoiMzk0M2EwZmZmMGRjNDQ1YWI4NTVkZGMyYTM1ZjUxZjgiLCJwIjoiaiJ9
- 비밀번호 재설정 플로우에 API를 연결
- 이메일 인증 화면 내 상태 관리 방식 수정
- 엑세스 토큰이 없는 경우 HeaderInterceptor에서 제거
-  회원가입 뷰모델 내 선언되어 있던 VerifiedState를 Auth 모듈 내에서 공용으로 사용하도록 수정했습니다.
이 변경사항으로 인해 회원가입 코드 내에도 약간의 수정이 발생했습니다.
- 비밀번호 재설정 플로우에서 뒤로 가기 버튼에 대한 처리를 위하 상태관리 방식을 대폭 수정했습니다.
- 인증코드 상태 값을 뷰모델 내부에서 관리
- 뷰모델 내 모든 변수의 setter를 은닉화하고 update용 함수 구현
- 비밀번호 재설정 화면에서 이메일 인증화면으로 복귀할 경우, 모든 상태들이 초기화되도록 구현했습니다.
- 4/23 회의에서 의논한 비밀번호 재설정 API의 토큰 관련 문제를 조건문 추가로 해결했습니다. [b3012cc](https://github.com/ku-ring/KU-Ring-Android/pull/478/commits/b3012cc34127c48310f983df2e27b7edd11f3c0e)
> kuring-235: 비밀번호 재설정 로직 

- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/User.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserClient.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/UserService.kt
- data/remote/src/test/java/com/ku_stacks/ku_ring/remote/UserServiceTest.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/AuthActivity.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signin/SignInNavigation.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signin/inner_screen/SignInScreen.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signout/SignOutViewModel.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreen.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingViewModel.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/groups/ProfileGroup.kt
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/SettingScreen.kt
- feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-235?atlOrigin=eyJpIjoiZmNjZTk5OTMyOGU5NDRlMmE1NWM3ODEzMDgwNzdhZTIiLCJwIjoiaiJ9
- 프로필 API 연결
- API 성공 여부에 따른 성공/오류/로딩 화면을 구현했습니다.ca08fd4557c5d48bc967cb666c050fadfe93dae7
- 로그아웃, 탈퇴, 회원정보 api 파라미터 수정
- 인터셉터 추가로 인해 잉여 파라미터가 된 토큰 헤더들을 삭제했습니다.
- AuthActivity 시작 애니메이션 추가 5f8006fd10da8b2572074dcfca8db8a2e9722a86
- 로그아웃 팝업 추가 46a51d80294f976337ab819d8b4fef08c2064175
https://github.com/user-attachments/assets/4c3d768f-3e3d-4df1-b687-69f965539b2d
> kuring-235: 설정화면 로직 구현

- build-logic/gradle/wrapper/gradle-wrapper.properties
- data/local/src/main/java/com/ku_stacks/ku_ring/local/di/DBModule.kt
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
Gradle: 8.13 -> 8.14
AGP: 8.9.1 -> 8.9.2
ksp: 2.1.20-1.0.32 -> 2.1.20-2.0.0
hilt: 2.55 -> 2.56.2
compose-bom: 2025.03.01 -> 2025.04.01
lottie: 6.6.4 -> 6.6.6
> [feature/bump-version-and-ksp] 주요 라이브러리 업데이트

- core/util/src/main/java/com/ku_stacks/ku_ring/util/ThrowableUtil.kt
- data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordViewModel.kt
- feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signup/SignUpViewModel.kt
- feature/auth/src/main/res/values/strings.xml
- feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingViewModel.kt
- feature/splash/build.gradle.kts
- feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
- feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashViewModel.kt
- feature/splash/src/test/java/com/ku_stacks/ku_ring/splash/SplashViewModelTest.kt
- 회원정보 API에 토큰 관리 로직 추가
- "계정 없음", "유효하지 않은 토큰"과 같은 오류 발생 시 기기 내 저장된 토큰 삭제
- Throwable 확장함수의 반환값을 문자열에서 데이터클래스로 수정
- 입력 필드 내 문자열 "힉교" -> "학교"로 수정
- 설정화면 내 상태관리 방식을 Exception 타입에 따라 나누는 걸로 재수정했습니다.
인터넷 연결 오류의 경우에만 에러화면을 띄우고, 나머지의 경우엔 토큰을 지우고 비로그인 화면이 띄워집니다.
- 기능 구현은 이것으로 끝입니다! 이번주동안 개인적으로 테스트해보고 미흡한 부분 있으면 fix PR 올리도록 할게요!
> kuring-235: 회원정보 및 토큰 관리

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/comment/Comment.kt
- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/PlainNoticeComment.kt
- data/noticecomment/src/main/java/com/ku_stacks/ku_ring/noticecomment/mapper/ResponseToDomain.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/noticecomment/response/NoticeCommentResponse.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebScreen.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebViewModel.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/CommentsBottomSheet.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/PreviewData.kt
- feature/notice_detail/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-234?atlOrigin=eyJpIjoiMTEyZTA4M2E1MzAzNGY2NDgyMDU1NDQxODhlMWUwNGEiLCJwIjoiaiJ9
댓글 삭제 로직을 구현했습니다.
**주의: 현재 댓글 추가/삭제 시 간헐적으로 UI가 업데이트되지 않는 문제가 있습니다. 해결 중입니다.**
삭제 버튼을 누르면 팝업을 띄우고, 팝업의 `삭제하기` 버튼을 누르면 댓글이 삭제됩니다.
댓글 구현 끝!
~현재 댓글 API 응답으로는 댓글 작성자가 자신인지 확인할 수 없는 문제가 있습니다. 이 문제는 내일 회의에서 논의 예정입니다.~ API 응답에 bool 필드를 추가하기로 결정됐고,https://github.com/ku-ring/KU-Ring-Android/pull/492/commits/eda772bdf1c540368ccab6832780b6089412e7b0 에서 작업 완료했습니다.
> kuring-234 댓글 삭제 로직 구현

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/comment/Comment.kt
- data/domain/src/main/java/com/ku_stacks/ku_ring/domain/PlainNoticeComment.kt
- data/noticecomment/src/main/java/com/ku_stacks/ku_ring/noticecomment/mapper/ResponseToDomain.kt
- data/remote/src/main/java/com/ku_stacks/ku_ring/remote/noticecomment/response/NoticeCommentResponse.kt
- domain/noticecomment/src/main/java/com/ku_stacks/ku_ring/domain/noticecomment/usecase/GetNoticeCommentPagingSource.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebScreen.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebViewModel.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/CommentTextField.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/CommentsBottomSheet.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/LazyPagingCommentColumn.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/PreviewData.kt
- feature/notice_detail/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-234?atlOrigin=eyJpIjoiMTEyZTA4M2E1MzAzNGY2NDgyMDU1NDQxODhlMWUwNGEiLCJwIjoiaiJ9
댓글/대댓글 작성 로직을 구현했습니다.
댓글 작성 로직을 살펴보기 전에, `GetNoticeCommentPagingSource`의 변경점을 살펴보겠습니다. 이 변경점은 매우 중요합니다.
이제 페이지를 로드한 후, 다음 페이지가 항상 로드됩니다. 그러나 3초 안에 같은 페이지 로드를 반복할 경우 로드가 즉시 실패합니다. **실패된 로드는 `LazyPagingItems#retry`를 호출하여 재시도할 수 있습니다.**
댓글을 작성하면 `LazyPagingItems#retry`가 호출됩니다. 이 함수는 직전에 실패한 로드를 재실행합니다. 직전에 실패한 로드는 항상 '다음 페이지 로드'이므로, 새로 작성한 댓글이 항상 로드될 수 있습니다.
대댓글을 작성하면 `LazyPagingItems#refresh`가 호출됩니다. 이 함수는 `PagingSource`와 `PagingData` 인스턴스를 새로 만드는 역할을 합니다. 쉽게 말하면 데이터를 다시 로드하는 역할입니다. 따라서 대댓글이 UI에 로드되어 보이게 됩니다.
`HeaderInterceptor.kt`의 48번 라인을, 노션 `Android > 회원가입/댓글 API 임시 토큰` 문서의 `액세스 토큰`으로 수정하고, `:data:remote`의 build.gradle에서 debug API 주소를 release와 같은 주소로 변경하면 댓글 추가 기능을 …
> kuring-234 댓글/대댓글 작성 로직 구현

- core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/comment/Comment.kt
- feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/LazyPagingCommentColumn.kt
구분선 굵기를 얇게 수정했습니다. (as-is → to-be)
대댓글에는 대댓글 아이콘을 보여주지 않습니다.
> [댓글 QA] 구분선, 대댓글 아이콘
