ku-ring/KU-Ring-Android

.idea/misc.xml, app/src/main/java/com/ku_stacks/ku_ring/ui/notice_webview/NoticeActivity.kt, app/src/main/res/drawable/ic_share.xml, app/src/main/res/layout/activity_notice.xml, app/src/main/res/values/strings.xml
- NoticeActivity의 상단바에 공지 공유하기 버튼 클릭시 공유할 외부 앱을 선택할 수 있다.
- NoticeActivity에 UI요소가 많아짐에 따라 ViewBinding 을 추가
=> [기능 추가] 공지 공유 기능 추가

.idea/misc.xml, app/src/main/java/com/ku_stacks/ku_ring/ui/dialogs/KuringDialog.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionViewModel.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/my_notification/NotificationActivity.kt, app/src/main/java/com/ku_stacks/ku_ring/util/ContextExt.kt, app/src/main/res/drawable/bg_dialog_kuring.xml, app/src/main/res/layout/dialog_kuring.xml, app/src/main/res/values-night/colors.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
- 쿠링에서 범용적으로 사용될 커스텀 다이얼로그 생성
- 코틀린 확장함수로 만든 Context.makeDialog() 함수로 ActivityContext에서 언제든 간단하게 호출 가능
- 만약 다이얼로그에서 확인 버튼에 대한 이벤트 처리를 하고 싶다면 makeDialog()의 반환값인 dialog에서 `setOnConfirmClickListener()` 으로 인터페이스 재정의 가능
=> [유틸] 쿠링 커스텀 다이얼로그 추가

app/src/main/java/com/ku_stacks/ku_ring/data/api/DepartmentClient.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/DepartmentService.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/NoticeClient.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/NoticeService.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentDataResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentListResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentNoticeDataResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentNoticeListResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentNoticeResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/api/response/DepartmentResponse.kt, app/src/main/java/com/ku_stacks/ku_ring/data/db/DepartmentDao.kt, app/src/main/java/com/ku_stacks/ku_ring/data/db/DepartmentEntity.kt, app/src/main/java/com/ku_stacks/ku_ring/data/db/KuRingDatabase.kt, app/src/main/java/com/ku_stacks/ku_ring/data/mapper/EntityToModelMapper.kt, app/src/main/java/com/ku_stacks/ku_ring/data/mapper/ModelToEntityMapper.kt, app/src/main/java/com/ku_stacks/ku_ring/data/model/Department.kt, app/src/main/java/com/ku_stacks/ku_ring/di/DBModule.kt, app/src/main/java/com/ku_stacks/ku_ring/di/NetworkModule.kt, app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepository.kt, app/src/main/java/com/ku_stacks/ku_ring/repository/DepartmentRepositoryImpl.kt
학과별 공지 PR은 학과 데이터 -> 공지 데이터(학과별 공지에 맞게 리팩토링) -> UI 순으로 올리려고 합니다.
----------
학과 API, Room entity, DAO, Repository 코드를 작성했습니다. 자세한 내용은 코멘트로 추가하겠습니다.
=> [추가] 학과 로직 코드 (데이터베이스~Repository)

app/src/main/java/com/ku_stacks/ku_ring/ui/compose/NonLazyGrid.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/compose/theme/Color.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/compose/theme/KuringTheme.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/compose/theme/Typography.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/EditSubscriptionActivity.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/SubscriptionDrawer.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/edit_subscription/compose/Subscriptions.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/NoticesPagerAdapter.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/NoticesParentFragment.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/DepartmentNoticeFragment.kt, app/src/main/java/com/ku_stacks/ku_ring/ui/main/notice/department/DepartmentNoticeViewModel.kt, app/src/main/res/drawable/ic_add_circle.xml, app/src/main/res/layout/fragment_department_notice.xml, app/src/main/res/values/strings.xml
학과별공지 화면 XML과 공통 로직 코드를 추가했습니다.
=> [추가] 학과별공지 화면 틀 추가

app/build.gradle
=> [수정] 디버그 서버 URL을 바뀐 URL로 수정

.github/workflows/android-develop.yml
https://kuring.atlassian.net/browse/KURING-119
develop 브랜치처럼 push/pr 시 ci 돌도록 합니다
=> kuring-119 2.0/base 브랜치에 PR 시 ci 추가

app/src/main/java/com/ku_stacks/ku_ring/navigator/KuringNavigatorImpl.kt, common/thirdparty/src/main/java/com/ku_stacks/ku_ring/thirdparty/firebase/MyFireBaseMessagingService.kt, common/ui_util/src/main/java/com/ku_stacks/ku_ring/ui_util/KuringNavigator.kt, common/ui_util/src/main/res/drawable/ic_share.xml, data/domain/src/main/java/com/ku_stacks/ku_ring/domain/WebViewNotice.kt, data/domain/src/main/java/com/ku_stacks/ku_ring/domain/mapper/ModelToModelMapper.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainActivity.kt, feature/my_notification/src/main/java/com/ku_stacks/ku_ring/my_notification/mapper/UiModelToModelMapper.kt, feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/NoticeWebActivity.kt, feature/notice_detail/src/main/res/drawable/ic_share.xml, feature/notice_detail/src/main/res/layout/activity_notice_web.xml, feature/splash/src/main/java/com/ku_stacks/ku_ring/splash/SplashActivity.kt
https://kuring.atlassian.net/browse/KURING-103
이쪽 화면은 웹뷰 화면이라 디자인상 큰 차이가 없고 일정이 넉넉치 못하여 compose 로는 차마 못바꿨습니다
- 공지 상세 상단에 subject 노출
- 공지 상세 상단에 share icon 변경
- <img width="334" alt="image" src="https://github.com/ku-ring/KU-Ring-Android/assets/45001093/5c0a9e32-7844-4cd2-93bb-afa0db8e7eea">
=> Kuring-103 공지상세 웹뷰 디자인 2.0

feature/edit_subscription/src/main/java/com/ku_stacks/ku_ring/edit_subscription/compose/EditSubscriptionScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/DepartmentNoticeScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/search/compose/inner_screen/StaffSearchScreen.kt
https://kuring.atlassian.net/browse/KURING-153?atlOrigin=eyJpIjoiMTY5OTYyODkxYTBhNGMzNzlhYjk3NTZjYTZjYTJkM2QiLCJwIjoiaiJ9
일부 페이지에서 잘못된 UI를 보여주고 있어 자체 QA를 진행했습니다. 대부분 간단하게 고칠 수 있었습니다.
수정 내용은 아래 사진으로 갈음합니다. (before → after)
끝!!!
QA 잘 마무리했으면 좋겠네요
=> kuring-153 2.0 디자인 자체 QA

common/designsystem/src/main/res/drawable/ic_external_link_v2.xml, feature/main/src/main/AndroidManifest.xml, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingFragment.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/OpenSourceActivity.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingDestinations.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingNavHost.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/components/OpenSourceItem.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceEmojiScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceListScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/SettingScreen.kt, feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-154?atlOrigin=eyJpIjoiNDNlMzBhNzZhZWVhNDYyOTg4ZTJjMTViZDU5ZjVmMzEiLCJwIjoiaiJ9
오픈소스 UI를 추가했습니다. 임시로 Activity를 사용하고 있는데, 향후 migrage할 때 제거할 예정입니다. (메인 모듈을 단일 activity로 합칠 예정)
UI 내부 이동은 Navigation을 적용했습니다. 추후 main 모듈을 compose로 migrate할 때, main navigation graph에 흡수될 예정입니다.
=> kuring-154 오픈소스 UI 추가

common/designsystem/src/main/res/drawable/ic_external_link_v2.xml, data/department/src/main/java/com/ku_stacks/ku_ring/department/mapper/DomainToEntity.kt, data/department/src/main/java/com/ku_stacks/ku_ring/department/mapper/EntityToDomain.kt, data/department/src/main/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepository.kt, data/department/src/main/java/com/ku_stacks/ku_ring/department/repository/DepartmentRepositoryImpl.kt, data/local/src/main/java/com/ku_stacks/ku_ring/local/di/DBModule.kt, data/local/src/main/java/com/ku_stacks/ku_ring/local/entity/DepartmentEntity.kt, data/local/src/main/java/com/ku_stacks/ku_ring/local/room/DepartmentDao.kt, data/local/src/testFixtures/java/com/ku_stacks/ku_ring/local/LocalFixtures.java, feature/edit_departments/src/main/java/com/ku_stacks/ku_ring/edit_departments/EditDepartmentsViewModel.kt, feature/main/src/main/AndroidManifest.xml, feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/DepartmentNoticeViewModel.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/SettingFragment.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/OpenSourceActivity.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingDestinations.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/SettingNavHost.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/components/OpenSourceItem.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceEmojiScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceListScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/OpenSourceScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/SettingScreen.kt, feature/main/src/main/res/values/strings.xml, feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/OnboardingViewModel.kt
https://kuring.atlassian.net/browse/KURING-154?atlOrigin=eyJpIjoiNDNlMzBhNzZhZWVhNDYyOTg4ZTJjMTViZDU5ZjVmMzEiLCJwIjoiaiJ9
대표 학과 로직을 추가했습니다. 커밋 메시지에는 `대표 공지`라고 적혀 있지만, `대표 학과`가 맞습니다.
학과 DB에 `isMainDepartment` 필드를 추가하고, 학과 추가/삭제 시 필드를 업데이트하는 로직을 구현했습니다.
=> kuring-154 대표 학과 로직 추가

feature/onboarding/src/main/java/com/ku_stacks/ku_ring/onboarding/compose/OnboardingViewModel.kt
https://kuring.atlassian.net/browse/KURING-156?atlOrigin=eyJpIjoiZTk2NWQzMTIxZWZhNGY1ODkzZjFhMGY0YzZjNzUyYmMiLCJwIjoiaiJ9
어제 논의 결과, 온보딩 화면에서 학과를 구독하면 알림도 받을 수 있도록 하자는 결론이 나왔습니다.
그래서 구현했습니다.
=> kuring-156 온보딩 화면에서 선택한 학과의 알림을 자동으로 활성화

app/build.gradle.kts, app/src/main/AndroidManifest.xml, data/notice/src/test/java/com/ku_stacks/ku_ring/notice/NoticeRepositoryTest.kt, feature/splash/build.gradle.kts, gradle.properties, gradle/libs.versions.toml
- signingRelease 태스크에서 keystoreFile을 projectroot/app/singing폴더가 아닌 로컬 기기의 루트/app/signing에서 찾고 있어서 폴더 경로 명시적으로 적었습니다....
=> [feature/replace-file-expression] assembleRelease 에러 fix

data/local/src/main/java/com/ku_stacks/ku_ring/local/room/SearchHistoryDao.kt, data/search/src/main/java/com/example/search/repository/SearchHistoryRepository.kt, data/search/src/main/java/com/example/search/repository/SearchHistoryRepositoryImpl.kt, data/search/src/test/java/com/example/search/SearchHistoryRepositoryImplTest.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/search/SearchViewModel.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/search/compose/SearchScreen.kt
https://kuring.atlassian.net/browse/KURING-164
- insert 한 최근 검색어 데이터 로드 (넣은 역순)
- 최근검색어 클릭 이벤트 처리
- 검색 및 최근검색어로 다시 추가
- `전체 삭제` 클릭 이벤트 처리 및 애니메이션 처리
https://github.com/ku-ring/KU-Ring-Android/assets/45001093/d07716bc-5762-470e-b410-f6a1d9b761eb
=> Kuring-162 검색 - 최근검색어 기능 추가 2

README.md
README에서 앱 소개 이미지가 작게 보이던 문제를 해결했습니다.
=> [수정] 앱 소개 이미지가 작게 보이던 문제 해결

.gitignore, .idea/kotlinc.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/ku_stacks/ku_ring/KuRingApplication.kt, build-logic/build.gradle.kts, build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/ApplicationPlugin.kt, build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/convention/KotlinJvmPlugin.kt, build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/primitive/ComposePlugin.kt, build-logic/src/main/kotlin/com/ku_stacks/ku_ring/buildlogic/primitive/KotlinPlugin.kt, build.gradle.kts, data/local/build.gradle.kts, data/local/src/main/java/com/ku_stacks/ku_ring/local/di/DBModule.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainActivity.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
- SmokeTest/Build 다 정상동작하는 것 확인했습니다.
=> [feature/bump-versions] Kotlin/Gradle/Library 버전 올리기

gradle/libs.versions.toml
- targetSdk 34로 올리기 (8/31 타깃 sdk 대응)
=> [feature/bump-target-sdk] targetSdk 34로 올리기

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/ku_stacks/ku_ring/navigator/KuringNavigatorImpl.kt, core/preferences/src/main/java/com/ku_stacks/ku_ring/preferences/PreferenceUtil.kt, core/ui_util/src/main/java/com/ku_stacks/ku_ring/ui_util/KuringNavigator.kt, feature/kuringbot/src/main/java/com/ku_stacks/ku_ring/kuringbot/KuringBotActivity.kt, feature/kuringbot/src/main/java/com/ku_stacks/ku_ring/kuringbot/compose/KuringBotScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreen.kt, feature/main/src/main/java/com/ku_stacks/ku_ring/main/MainScreenFab.kt, feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-188?atlOrigin=eyJpIjoiMTJjYWFlMDYzNmRkNDkzYzkxZTViZDBjNDZlNDI3NmUiLCJwIjoiaiJ9
마지막 PR입니다. 쿠링봇 UI를 구현하였고, 1차 QA 사항을 적용하였습니다. 
이 PR 기준으로 2차 QA 요청했습니다.
=> kuring-187 쿠링봇 UI 구현

feature/kuringbot/src/main/java/com/ku_stacks/ku_ring/kuringbot/KuringBotViewModel.kt, feature/main/build.gradle.kts, gradle/libs.versions.toml
https://kuring.atlassian.net/browse/KURING-203?atlOrigin=eyJpIjoiZDEzZTZhYTMwZDlkNGNlNTliYzMxZWQxOGU0Y2NkMjQiLCJwIjoiaiJ9
쿠링봇 QA를 완료하였고, QA용으로 남겨두었던 디버그 코드를 제거했습니다.
일부 사용하지 않는 라이브러리도 제거했습니다.
=> kuring-203 쿠링봇 QA 마무리 및 출시 준비 완료

feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-215?atlOrigin=eyJpIjoiMTdiNjUwZjNlMmViNGU5ZWI1ZTViMmY0Yjc3ZjFlYjAiLCJwIjoiaiJ9
새로 작성된 팀 소개 페이지를 앱에 적용하였습니다.
끝!
=> feature: 새로운 팀 소개 링크 적용

app/build.gradle.kts
https://kuring.atlassian.net/browse/KURING-220?atlOrigin=eyJpIjoiMjIzOTdiZDNjZTRhNGYyYWI1NWY1ODBhYzI5ZTFhMjUiLCJwIjoiaiJ9
사용되지도 않으면서 빌드만 방해하는 build config를 제거했습니다.
=> gradle: 사용하지 않는 build config 제거

.github/auto_assign.yml
=> Auto assign에 석준님 추가

feature/main/src/main/java/com/ku_stacks/ku_ring/main/setting/compose/inner_screen/SettingScreen.kt, feature/main/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-214?atlOrigin=eyJpIjoiM2EzNTc4ZjI2NzYwNDYwOTgwM2Y1YmMxOTY1Zjg5YTMiLCJwIjoiaiJ9
요약
---
앱 내 더보기란에 쿠링 멤버들 이름 추가했습니다.
스크린샷
---
=> feat: 앱 내 더보기란 개발자 등록

.github/auto_assign.yml
제 깃허브 아이디를 수정해서 auto_assign 파일을 수정했습니다!
`boiledEgg-s`    ➡   `boiledeggg`
=> Auto Assign 아이디 수정

core/util/src/main/java/com/ku_stacks/ku_ring/util/Context.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/AuthDestination.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/AuthScreen.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/PasswordInputGroup.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/PasswordInputGroupState.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/component/PasswordInputState.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordNavigation.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordSideEffect.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/ResetPasswordViewModel.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/inner_screen/EmailVerificationScreen.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/reset_password/inner_screen/ResetPasswordScreen.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signin/SignInNavigation.kt, feature/auth/src/main/res/values/strings.xml
https://kuring.atlassian.net/browse/KURING-231?atlOrigin=eyJpIjoiZmUxMjU5MDg4NjI1NDEyOWFkODdlNjA1N2IzOTk1MTkiLCJwIjoiaiJ9
- 이메일 인증, 비밀번호 확인 UI 구현
- 뷰모델 및 mock API 연결
- 건국메일 이동로직 추가
- 비밀번호 입력 컴포넌트 분리 및 적용
- 네비게이션 연결
https://github.com/user-attachments/assets/51297ae8-4b28-45f9-b74e-0948850018dd
=> kuring-231: 비밀번호 찾기 UI 구현

feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signin/inner_screen/SignInDialog.kt, feature/auth/src/main/res/values/strings.xml
=> kuring-231: 로그인 다이얼로그 수정

data/remote/src/main/java/com/ku_stacks/ku_ring/remote/user/response/SignInResponse.kt, data/user/src/main/java/com/ku_stacks/ku_ring/user/repository/UserRepositoryImpl.kt, feature/auth/src/main/java/com/ku_stacks/ku_ring/auth/compose/signin/SignInViewModel.kt
https://kuring.atlassian.net/browse/KURING-235?atlOrigin=eyJpIjoiZjdmZGJjOTdlNDc2NGI3NGExMGZiYmU1NjVhOGM3NDIiLCJwIjoiaiJ9
- SignInViewModel 내부에 잘못 연결된 API 수정 e0c0edc4f3ad1246f7a37ecce14a8f31d41beaa0
- UserRepository에서 수신한 응답 데이터를 처리하는 방식 수정 8c1343042273660396d1670c80532b469d67dc5f
- 응답 Dto의 isSuccess getter 수정 7e207c7c6a08118219e7786f18b5b4ccdd9f269f
=> kuring-235: 로그인 로직 수정

core/designsystem/src/main/java/com/ku_stacks/ku_ring/designsystem/components/comment/Comment.kt, core/designsystem/src/main/res/drawable/ic_more_vertical_v2.xml, core/designsystem/src/main/res/values/strings.xml, feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/component/LazyPagingCommentColumn.kt
댓글 dropdown 메뉴를 추가했습니다. 메뉴에는 신고, 삭제(자기 댓글일 때에만) 항목이 존재합니다.
신고 버튼은 무감 상태로 구현했습니다. 신고 API가 완성되면 연결할 예정입니다.
=> QA: 댓글 dropdown 메뉴 추가

data/noticecomment/src/main/java/com/ku_stacks/ku_ring/noticecomment/NoticeCommentRepositoryImpl.kt, feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/noticeweb/NoticeWebScreen.kt, feature/notice_detail/src/main/java/com/ku_stacks/ku_ring/notice_detail/noticeweb/NoticeWebViewModel.kt
금칙어 제한을 의미하는 422 응답 코드를 받아, 토스트 메시지를 보여줍니다.
=> [댓글 QA] 금칙어 응답 처리
